### ISSUE TITLE
Setting Proxy is missleading

### ISSUE THREAD

**Issue by SecMyth** [vulnersCom/burp-vulners-scanner#2]
I noticed that activating the use of a proxy and afterwards changing the proxies host and port will not set the proxy correctly. Only changing the option to use a proxy will finally set the altered settings.
for example:

1. Select "Proxy enabled"
1. Change the Host name to abcd.com
1. Internally still the old host is used
1. deactivate and active the "Proxy enabled" option
1. Now the host abcd.com is used to contact https://vulners.com

**Comment by SecMyth** [comment]
Suggestion: in /src/main/java/burp/gui/TabComponent.java add changeListener for both text fields as well to call setProxy() [according to getProxyChangeListener()]

**Comment by vankyver** [comment]
Hi, thanks for your report!
Fixed. Could you please confirm it for latest release?

**Comment by SecMyth** [comment]
For me it looks like the proxy feature isn't working at all.

**Comment by Hipapheralkus** [comment]
I also face the same issue -> I'm using the latest version (from BApp store). My setup it behind firewall so I need to use proxy, and when I enter proxy from which the data file is accessible, and then try to load the resource, I don't get anything. There are no errors, but no data as well. 
What works for me, if I set "vulners.com" in Burp User settings upstream proxy.

**Comment by vankyver** [comment]
Issue finally fixed in 1.2
Now it's using native burp proxy
